/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as UploadOwnershipPolicyRouteImport } from './routes/upload-ownership-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SeoAuditRouteImport } from './routes/seo-audit'
import { Route as SemrushRouteImport } from './routes/semrush'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchConsoleRouteImport } from './routes/search-console'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiContentPolicyRouteImport } from './routes/ai-content-policy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamChatRouteImport } from './routes/_authenticated/team-chat'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedHelpSupportRouteImport } from './routes/_authenticated/help-support'
import { Route as AuthenticatedGlobalDashboardRouteImport } from './routes/_authenticated/global-dashboard'
import { Route as AuthenticatedDemoTemplatesRouteImport } from './routes/_authenticated/demo-templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentCalendarRouteImport } from './routes/_authenticated/content-calendar'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChatbotAdminRouteImport } from './routes/_authenticated/chatbot-admin'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCampaignWizardRouteImport } from './routes/_authenticated/campaign-wizard'
import { Route as AuthenticatedCampaignFoldersRouteImport } from './routes/_authenticated/campaign-folders'
import { Route as AuthenticatedBusinessProfileRouteImport } from './routes/_authenticated/business-profile'
import { Route as AuthenticatedAutoCampaignRouteImport } from './routes/_authenticated/auto-campaign'
import { Route as AuthenticatedAiWriterRouteImport } from './routes/_authenticated/ai-writer'
import { Route as AuthenticatedAiVideoStudioRouteImport } from './routes/_authenticated/ai-video-studio'
import { Route as AuthenticatedAiStudioRouteImport } from './routes/_authenticated/ai-studio'
import { Route as AuthenticatedAiStrategyConsultantRouteImport } from './routes/_authenticated/ai-strategy-consultant'
import { Route as AuthenticatedAiSeoPpcConsultantRouteImport } from './routes/_authenticated/ai-seo-ppc-consultant'
import { Route as AuthenticatedAccountPrivacyRouteImport } from './routes/_authenticated/account-privacy'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadOwnershipPolicyRoute = UploadOwnershipPolicyRouteImport.update({
  id: '/upload-ownership-policy',
  path: '/upload-ownership-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditRoute = SeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SemrushRoute = SemrushRouteImport.update({
  id: '/semrush',
  path: '/semrush',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchConsoleRoute = SearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiContentPolicyRoute = AiContentPolicyRouteImport.update({
  id: '/ai-content-policy',
  path: '/ai-content-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamChatRoute = AuthenticatedTeamChatRouteImport.update({
  id: '/team-chat',
  path: '/team-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpSupportRoute =
  AuthenticatedHelpSupportRouteImport.update({
    id: '/help-support',
    path: '/help-support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGlobalDashboardRoute =
  AuthenticatedGlobalDashboardRouteImport.update({
    id: '/global-dashboard',
    path: '/global-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoTemplatesRoute =
  AuthenticatedDemoTemplatesRouteImport.update({
    id: '/demo-templates',
    path: '/demo-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentCalendarRoute =
  AuthenticatedContentCalendarRouteImport.update({
    id: '/content-calendar',
    path: '/content-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatbotAdminRoute =
  AuthenticatedChatbotAdminRouteImport.update({
    id: '/chatbot-admin',
    path: '/chatbot-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignWizardRoute =
  AuthenticatedCampaignWizardRouteImport.update({
    id: '/campaign-wizard',
    path: '/campaign-wizard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignFoldersRoute =
  AuthenticatedCampaignFoldersRouteImport.update({
    id: '/campaign-folders',
    path: '/campaign-folders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessProfileRoute =
  AuthenticatedBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutoCampaignRoute =
  AuthenticatedAutoCampaignRouteImport.update({
    id: '/auto-campaign',
    path: '/auto-campaign',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiWriterRoute = AuthenticatedAiWriterRouteImport.update({
  id: '/ai-writer',
  path: '/ai-writer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiVideoStudioRoute =
  AuthenticatedAiVideoStudioRouteImport.update({
    id: '/ai-video-studio',
    path: '/ai-video-studio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioRoute = AuthenticatedAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiStrategyConsultantRoute =
  AuthenticatedAiStrategyConsultantRouteImport.update({
    id: '/ai-strategy-consultant',
    path: '/ai-strategy-consultant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiSeoPpcConsultantRoute =
  AuthenticatedAiSeoPpcConsultantRouteImport.update({
    id: '/ai-seo-ppc-consultant',
    path: '/ai-seo-ppc-consultant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountPrivacyRoute =
  AuthenticatedAccountPrivacyRouteImport.update({
    id: '/account-privacy',
    path: '/account-privacy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-content-policy': typeof AiContentPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/index': typeof Char91indexChar93Route
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-console': typeof SearchConsoleRoute
  '/security': typeof SecurityRoute
  '/semrush': typeof SemrushRoute
  '/seo-audit': typeof SeoAuditRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/upload-ownership-policy': typeof UploadOwnershipPolicyRoute
  '/account-privacy': typeof AuthenticatedAccountPrivacyRoute
  '/ai-seo-ppc-consultant': typeof AuthenticatedAiSeoPpcConsultantRoute
  '/ai-strategy-consultant': typeof AuthenticatedAiStrategyConsultantRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/ai-video-studio': typeof AuthenticatedAiVideoStudioRoute
  '/ai-writer': typeof AuthenticatedAiWriterRoute
  '/auto-campaign': typeof AuthenticatedAutoCampaignRoute
  '/business-profile': typeof AuthenticatedBusinessProfileRoute
  '/campaign-folders': typeof AuthenticatedCampaignFoldersRoute
  '/campaign-wizard': typeof AuthenticatedCampaignWizardRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/chatbot-admin': typeof AuthenticatedChatbotAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/content-calendar': typeof AuthenticatedContentCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo-templates': typeof AuthenticatedDemoTemplatesRoute
  '/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/help-support': typeof AuthenticatedHelpSupportRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team-chat': typeof AuthenticatedTeamChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-content-policy': typeof AiContentPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/index': typeof Char91indexChar93Route
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-console': typeof SearchConsoleRoute
  '/security': typeof SecurityRoute
  '/semrush': typeof SemrushRoute
  '/seo-audit': typeof SeoAuditRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/upload-ownership-policy': typeof UploadOwnershipPolicyRoute
  '/account-privacy': typeof AuthenticatedAccountPrivacyRoute
  '/ai-seo-ppc-consultant': typeof AuthenticatedAiSeoPpcConsultantRoute
  '/ai-strategy-consultant': typeof AuthenticatedAiStrategyConsultantRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/ai-video-studio': typeof AuthenticatedAiVideoStudioRoute
  '/ai-writer': typeof AuthenticatedAiWriterRoute
  '/auto-campaign': typeof AuthenticatedAutoCampaignRoute
  '/business-profile': typeof AuthenticatedBusinessProfileRoute
  '/campaign-folders': typeof AuthenticatedCampaignFoldersRoute
  '/campaign-wizard': typeof AuthenticatedCampaignWizardRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/chatbot-admin': typeof AuthenticatedChatbotAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/content-calendar': typeof AuthenticatedContentCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo-templates': typeof AuthenticatedDemoTemplatesRoute
  '/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/help-support': typeof AuthenticatedHelpSupportRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team-chat': typeof AuthenticatedTeamChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ai-content-policy': typeof AiContentPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/index': typeof Char91indexChar93Route
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-console': typeof SearchConsoleRoute
  '/security': typeof SecurityRoute
  '/semrush': typeof SemrushRoute
  '/seo-audit': typeof SeoAuditRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/upload-ownership-policy': typeof UploadOwnershipPolicyRoute
  '/_authenticated/account-privacy': typeof AuthenticatedAccountPrivacyRoute
  '/_authenticated/ai-seo-ppc-consultant': typeof AuthenticatedAiSeoPpcConsultantRoute
  '/_authenticated/ai-strategy-consultant': typeof AuthenticatedAiStrategyConsultantRoute
  '/_authenticated/ai-studio': typeof AuthenticatedAiStudioRoute
  '/_authenticated/ai-video-studio': typeof AuthenticatedAiVideoStudioRoute
  '/_authenticated/ai-writer': typeof AuthenticatedAiWriterRoute
  '/_authenticated/auto-campaign': typeof AuthenticatedAutoCampaignRoute
  '/_authenticated/business-profile': typeof AuthenticatedBusinessProfileRoute
  '/_authenticated/campaign-folders': typeof AuthenticatedCampaignFoldersRoute
  '/_authenticated/campaign-wizard': typeof AuthenticatedCampaignWizardRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/chatbot-admin': typeof AuthenticatedChatbotAdminRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/content-calendar': typeof AuthenticatedContentCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo-templates': typeof AuthenticatedDemoTemplatesRoute
  '/_authenticated/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/_authenticated/help-support': typeof AuthenticatedHelpSupportRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team-chat': typeof AuthenticatedTeamChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-content-policy'
    | '/auth'
    | '/blog'
    | '/book-demo'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/index'
    | '/privacy'
    | '/reset-password'
    | '/search-console'
    | '/security'
    | '/semrush'
    | '/seo-audit'
    | '/social'
    | '/terms'
    | '/upload-ownership-policy'
    | '/account-privacy'
    | '/ai-seo-ppc-consultant'
    | '/ai-strategy-consultant'
    | '/ai-studio'
    | '/ai-video-studio'
    | '/ai-writer'
    | '/auto-campaign'
    | '/business-profile'
    | '/campaign-folders'
    | '/campaign-wizard'
    | '/campaigns'
    | '/chatbot-admin'
    | '/clients'
    | '/content-calendar'
    | '/dashboard'
    | '/demo-templates'
    | '/global-dashboard'
    | '/help-support'
    | '/leads'
    | '/meetings'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/team-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-content-policy'
    | '/auth'
    | '/blog'
    | '/book-demo'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/index'
    | '/privacy'
    | '/reset-password'
    | '/search-console'
    | '/security'
    | '/semrush'
    | '/seo-audit'
    | '/social'
    | '/terms'
    | '/upload-ownership-policy'
    | '/account-privacy'
    | '/ai-seo-ppc-consultant'
    | '/ai-strategy-consultant'
    | '/ai-studio'
    | '/ai-video-studio'
    | '/ai-writer'
    | '/auto-campaign'
    | '/business-profile'
    | '/campaign-folders'
    | '/campaign-wizard'
    | '/campaigns'
    | '/chatbot-admin'
    | '/clients'
    | '/content-calendar'
    | '/dashboard'
    | '/demo-templates'
    | '/global-dashboard'
    | '/help-support'
    | '/leads'
    | '/meetings'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/team-chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-content-policy'
    | '/auth'
    | '/blog'
    | '/book-demo'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/index'
    | '/privacy'
    | '/reset-password'
    | '/search-console'
    | '/security'
    | '/semrush'
    | '/seo-audit'
    | '/social'
    | '/terms'
    | '/upload-ownership-policy'
    | '/_authenticated/account-privacy'
    | '/_authenticated/ai-seo-ppc-consultant'
    | '/_authenticated/ai-strategy-consultant'
    | '/_authenticated/ai-studio'
    | '/_authenticated/ai-video-studio'
    | '/_authenticated/ai-writer'
    | '/_authenticated/auto-campaign'
    | '/_authenticated/business-profile'
    | '/_authenticated/campaign-folders'
    | '/_authenticated/campaign-wizard'
    | '/_authenticated/campaigns'
    | '/_authenticated/chatbot-admin'
    | '/_authenticated/clients'
    | '/_authenticated/content-calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo-templates'
    | '/_authenticated/global-dashboard'
    | '/_authenticated/help-support'
    | '/_authenticated/leads'
    | '/_authenticated/meetings'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/team-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AiContentPolicyRoute: typeof AiContentPolicyRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BookDemoRoute: typeof BookDemoRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DemoRoute: typeof DemoRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchConsoleRoute: typeof SearchConsoleRoute
  SecurityRoute: typeof SecurityRoute
  SemrushRoute: typeof SemrushRoute
  SeoAuditRoute: typeof SeoAuditRoute
  SocialRoute: typeof SocialRoute
  TermsRoute: typeof TermsRoute
  UploadOwnershipPolicyRoute: typeof UploadOwnershipPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-ownership-policy': {
      id: '/upload-ownership-policy'
      path: '/upload-ownership-policy'
      fullPath: '/upload-ownership-policy'
      preLoaderRoute: typeof UploadOwnershipPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit': {
      id: '/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof SeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semrush': {
      id: '/semrush'
      path: '/semrush'
      fullPath: '/semrush'
      preLoaderRoute: typeof SemrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-console': {
      id: '/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof SearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-content-policy': {
      id: '/ai-content-policy'
      path: '/ai-content-policy'
      fullPath: '/ai-content-policy'
      preLoaderRoute: typeof AiContentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-chat': {
      id: '/_authenticated/team-chat'
      path: '/team-chat'
      fullPath: '/team-chat'
      preLoaderRoute: typeof AuthenticatedTeamChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help-support': {
      id: '/_authenticated/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof AuthenticatedHelpSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/global-dashboard': {
      id: '/_authenticated/global-dashboard'
      path: '/global-dashboard'
      fullPath: '/global-dashboard'
      preLoaderRoute: typeof AuthenticatedGlobalDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-templates': {
      id: '/_authenticated/demo-templates'
      path: '/demo-templates'
      fullPath: '/demo-templates'
      preLoaderRoute: typeof AuthenticatedDemoTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-calendar': {
      id: '/_authenticated/content-calendar'
      path: '/content-calendar'
      fullPath: '/content-calendar'
      preLoaderRoute: typeof AuthenticatedContentCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatbot-admin': {
      id: '/_authenticated/chatbot-admin'
      path: '/chatbot-admin'
      fullPath: '/chatbot-admin'
      preLoaderRoute: typeof AuthenticatedChatbotAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-wizard': {
      id: '/_authenticated/campaign-wizard'
      path: '/campaign-wizard'
      fullPath: '/campaign-wizard'
      preLoaderRoute: typeof AuthenticatedCampaignWizardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-folders': {
      id: '/_authenticated/campaign-folders'
      path: '/campaign-folders'
      fullPath: '/campaign-folders'
      preLoaderRoute: typeof AuthenticatedCampaignFoldersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business-profile': {
      id: '/_authenticated/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof AuthenticatedBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auto-campaign': {
      id: '/_authenticated/auto-campaign'
      path: '/auto-campaign'
      fullPath: '/auto-campaign'
      preLoaderRoute: typeof AuthenticatedAutoCampaignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-writer': {
      id: '/_authenticated/ai-writer'
      path: '/ai-writer'
      fullPath: '/ai-writer'
      preLoaderRoute: typeof AuthenticatedAiWriterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-video-studio': {
      id: '/_authenticated/ai-video-studio'
      path: '/ai-video-studio'
      fullPath: '/ai-video-studio'
      preLoaderRoute: typeof AuthenticatedAiVideoStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio': {
      id: '/_authenticated/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AuthenticatedAiStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-strategy-consultant': {
      id: '/_authenticated/ai-strategy-consultant'
      path: '/ai-strategy-consultant'
      fullPath: '/ai-strategy-consultant'
      preLoaderRoute: typeof AuthenticatedAiStrategyConsultantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-seo-ppc-consultant': {
      id: '/_authenticated/ai-seo-ppc-consultant'
      path: '/ai-seo-ppc-consultant'
      fullPath: '/ai-seo-ppc-consultant'
      preLoaderRoute: typeof AuthenticatedAiSeoPpcConsultantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account-privacy': {
      id: '/_authenticated/account-privacy'
      path: '/account-privacy'
      fullPath: '/account-privacy'
      preLoaderRoute: typeof AuthenticatedAccountPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountPrivacyRoute: typeof AuthenticatedAccountPrivacyRoute
  AuthenticatedAiSeoPpcConsultantRoute: typeof AuthenticatedAiSeoPpcConsultantRoute
  AuthenticatedAiStrategyConsultantRoute: typeof AuthenticatedAiStrategyConsultantRoute
  AuthenticatedAiStudioRoute: typeof AuthenticatedAiStudioRoute
  AuthenticatedAiVideoStudioRoute: typeof AuthenticatedAiVideoStudioRoute
  AuthenticatedAiWriterRoute: typeof AuthenticatedAiWriterRoute
  AuthenticatedAutoCampaignRoute: typeof AuthenticatedAutoCampaignRoute
  AuthenticatedBusinessProfileRoute: typeof AuthenticatedBusinessProfileRoute
  AuthenticatedCampaignFoldersRoute: typeof AuthenticatedCampaignFoldersRoute
  AuthenticatedCampaignWizardRoute: typeof AuthenticatedCampaignWizardRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedChatbotAdminRoute: typeof AuthenticatedChatbotAdminRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContentCalendarRoute: typeof AuthenticatedContentCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoTemplatesRoute: typeof AuthenticatedDemoTemplatesRoute
  AuthenticatedGlobalDashboardRoute: typeof AuthenticatedGlobalDashboardRoute
  AuthenticatedHelpSupportRoute: typeof AuthenticatedHelpSupportRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamChatRoute: typeof AuthenticatedTeamChatRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountPrivacyRoute: AuthenticatedAccountPrivacyRoute,
  AuthenticatedAiSeoPpcConsultantRoute: AuthenticatedAiSeoPpcConsultantRoute,
  AuthenticatedAiStrategyConsultantRoute:
    AuthenticatedAiStrategyConsultantRoute,
  AuthenticatedAiStudioRoute: AuthenticatedAiStudioRoute,
  AuthenticatedAiVideoStudioRoute: AuthenticatedAiVideoStudioRoute,
  AuthenticatedAiWriterRoute: AuthenticatedAiWriterRoute,
  AuthenticatedAutoCampaignRoute: AuthenticatedAutoCampaignRoute,
  AuthenticatedBusinessProfileRoute: AuthenticatedBusinessProfileRoute,
  AuthenticatedCampaignFoldersRoute: AuthenticatedCampaignFoldersRoute,
  AuthenticatedCampaignWizardRoute: AuthenticatedCampaignWizardRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedChatbotAdminRoute: AuthenticatedChatbotAdminRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContentCalendarRoute: AuthenticatedContentCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoTemplatesRoute: AuthenticatedDemoTemplatesRoute,
  AuthenticatedGlobalDashboardRoute: AuthenticatedGlobalDashboardRoute,
  AuthenticatedHelpSupportRoute: AuthenticatedHelpSupportRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamChatRoute: AuthenticatedTeamChatRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AiContentPolicyRoute: AiContentPolicyRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BookDemoRoute: BookDemoRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DemoRoute: DemoRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchConsoleRoute: SearchConsoleRoute,
  SecurityRoute: SecurityRoute,
  SemrushRoute: SemrushRoute,
  SeoAuditRoute: SeoAuditRoute,
  SocialRoute: SocialRoute,
  TermsRoute: TermsRoute,
  UploadOwnershipPolicyRoute: UploadOwnershipPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
